<?php

namespace App\Http\Resources\Boshra;

use App\Models\MemberFamily;
use App\Models\PersonalInformation;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class ReportResource extends JsonResource
{

  //  public  $child_id , $Recommendation  , $summary ;
  public $additional;

    public function toArray(Request $request): array
    {
        $mother_name = '' ; $father_name = '' ; $birth_date = '' ; $father_age = 0 ;
        $father_cearer = '' ; $father_edu = '' ; $mother_age = 0  ; $mother_cearer = ''; $mother_edu = '' ;
        $mother_birth  = 0 ; $relative_relation ='' ; $check_disease = '' ; $check_disability = '';
        $child_rank = 1 ; $sister = 0 ; $brother = 0 ; $disease = ' ' ; $family = '' ;

        $birth_date = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 4)->value('answer') ;

        $mother_name = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 14)->value('answer') ;

        $mother_age = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 15)->value('answer') ;


        $mother_edu = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 16)->value('answer') ;

        $mother_cearer = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 17)->value('answer') ;

        $father_name = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 18)->value('answer') ;

        $father_age = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 19)->value('answer') ;

        $father_edu = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 20)->value('answer') ;

        $father_cearer = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 21)->value('answer') ;

        $mother_birth = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 23)->value('answer') ;

        $relative_relation = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 22)->value('answer') ;

        $check_disease = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 24)->value('answer') ;

        if($check_disease == 'لا')
        {
            $check_disease = 'لا يعاني الوالدين من أي مرض';
        }
        else{
            $check_disease = ' يعاني الوالدين من المرض';
        }

        $disease = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 25)->value('answer') ;

        $check_disability = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 26)->value('answer') ;

        if($check_disability == 'لا')
        {
            $check_disability = 'لا توجد حالة إعاقة في العائلة';
        }
        else{
            $check_disability = 'توجد حالة إعاقة في العائلة';
        }

        $child_rank = PersonalInformation::where('child_id' , $this->id)
        ->where('ques_id' , 30)->value('answer') ;


        $brother = MemberFamily::where('child_id' ,$this->child_id)
        ->where('gender' ,'ذكر')->count() ;

        $sister = MemberFamily::where('child_id' ,$this->child_id)
        ->where('gender' ,'!=' ,'ذكر')->count() ;

        if($sister == 0 && $brother == 0)
        {
            $family = 'ليس له إخوة' ;
        }
        else{
            $family = 'له من الإخوة '.$brother .'ذكر و ' .$sister.'أنثى' ;
        }

        $referral_reason = 'تمت إحالة الطفل من قبل الصحة المدرسية تربية دمشق لإجراء القحص الطبي والتربوي وبيان الرأي في إمكانية دخوله للمدارس الدامجة.';

        $family_info = 'يعيش الطفل مع والديه ، حيث يبلغ عمر الأب '.$father_age.'سنة وهو '.$father_cearer.'، ومستواه التعليمي '.$father_edu.'، '
        .'والأم '.$mother_cearer.'تبلغ من العمر '.$mother_age.' سنة ومستواها التعليمي '.$mother_edu.'، '.
        ' وكان عمر الأم عند إنجاب الطفل'.$mother_birth.'سنة ، وتوجد صلة قرابة بين الوالدين ('.$relative_relation.' )'
        .$check_disease.$disease.' ، '.$check_disability.' ، '.'والطفل ترتيبه في الأسرة '.$child_rank
        .$family .'.';

        return [

            'name' => 'الاسم : '.$this->name ,
            'phone' => 'هاتف : ' .$this->phone ,
            't_age' => 'العمر الزمني للطفل : '.$this->age ,
            'father' => 'اسم الأب : '.$father_name,
            'mother' => 'اسم الأم : '.$mother_name ,
            'birth_date' => $birth_date ,
            'referral_reason' => $referral_reason,
            'family_info' => $family_info

        ];
    }

    function additional(array $data)
    {
        return parent::additional($data); // TODO: Change the autogenerated stub
    }

    public function getAdditional(): array
    {
        return $this->additional;
    }


    public function setAdditional($additional)
    {
        $this->additional = $additional;
    }
}

/*
foreach ($this->personal_info as $val) {


            else  if($val['ques_id'] == 14)
            {
                $mother_name = $val['answer'] ;
            }
            else  if($val['ques_id'] == 15)
            {
                $mother_age = $val['answer'] ;
            }
            else  if($val['ques_id'] == 16)
            {
                $mother_edu = $val['answer'] ;
            }
            else  if($val['ques_id'] == 17)
            {
                $mother_cearer = $val['answer'] ;
            }
            else  if($val['ques_id'] == 18)
            {
                $father_name = $val['answer'] ;
            }
            else  if($val['ques_id'] == 19)
            {
                $father_age = $val['answer'] ;
            }
            else  if($val['ques_id'] == 20)
            {
                $father_edu = $val['answer'] ;
            }
            else  if($val['ques_id'] == 21)
            {
                $father_cearer = $val['answer'] ;
            }
            else  if($val['ques_id'] == 23)
            {
                $mother_birth = $val['answer'] ;
            }
            else  if($val['ques_id'] == 22)
            {
                $relative_relation = $val['answer'] ;
            }
            else  if($val['ques_id'] == 24)
            {
                if($val['answer'] == 'لا')
                {
                    $check_disease = 'لا يعاني الوالدين من أي مرض';
                }
                else{
                    $check_disease = ' يعاني الوالدين من المرض';
                }
            }
            else  if($val['ques_id'] == 25)
            {
                $disease = $val['answer'] ;
            }
            else  if($val['ques_id'] == 26)
            {
                if($val['answer'] == 'لا')
                {
                    $check_disability = 'لا توجد حالة إعاقة في العائلة';
                }
                else{
                    $check_disability = 'توجد حالة إعاقة في العائلة';
                }
            }
            else  if($val['ques_id'] == 30)
            {
                $child_rank = $val['answer'] ;
            }

        }

        $brother = MemberFamily::where('child_id' ,$this->child_id)
        ->where('gender' ,'ذكر')->count() ;

        $sister = MemberFamily::where('child_id' ,$this->child_id)
        ->where('gender' ,'!=' ,'ذكر')->count() ;

        if($sister == 0 && $brother == 0)
        {
            $family = 'ليس له إخوة' ;
        }
        else{
            $family = 'له من الإخوة '.$brother .'ذكر و ' .$sister.'أنثى' ;
        }
*/
